# Generated by Django 3.0.1 on 2019-12-19 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending authorization", "pending authorization"),
                            ("authorized", "authorized"),
                            ("pending capture", "pending capture"),
                            ("captured", "captured"),
                            ("pending cancellation", "pending cancellation"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("currency", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SalesChannelPaymentService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "payment_service",
                    models.CharField(
                        choices=[("giftcard", "giftcard")], max_length=255
                    ),
                ),
                (
                    "sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.SalesChannel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="saleschannelpaymentservice",
            constraint=models.UniqueConstraint(
                fields=("sales_channel", "payment_service"),
                name="payments_saleschannelpaymentservice_sales_channel_payment_service_unique",
            ),
        ),
    ]
