# Generated by Django 3.0.1 on 2019-12-19 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("code128", "code128"),
                            ("code39", "code39"),
                            ("ean", "ean"),
                            ("ean13", "ean13"),
                            ("ean14", "ean14"),
                            ("ean8", "ean8"),
                            ("gs1", "gs1"),
                            ("gs1_128", "gs1_128"),
                            ("gtin", "gtin"),
                            ("isbn", "isbn"),
                            ("isbn10", "isbn10"),
                            ("isbn13", "isbn13"),
                            ("issn", "issn"),
                            ("itf", "itf"),
                            ("jan", "jan"),
                            ("pzn", "pzn"),
                            ("upc", "upc"),
                            ("upca", "upca"),
                        ],
                        default="ean13",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FulfillmentCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "delivery_center",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_center",
                        to="core.DeliveryCenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("country", "country"),
                            ("sales channel", "sales channel"),
                        ],
                        default="country",
                        max_length=255,
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OnlineShop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SalesChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("app_label", "core"), ("model", "onlineshop")
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesChannelSupplierArticleManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SupplierFulfillmentCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fulfillment_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="core.FulfillmentCenter",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_centers",
                        to="core.Supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierFulfillmentCenterSalesChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_fulfillment_centers",
                        to="core.SalesChannel",
                    ),
                ),
                (
                    "supplier_fulfillment_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_channels",
                        to="core.SupplierFulfillmentCenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SupplierFulfillmentCenterSalesChannelMarket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_fulfillment_center_sales_channels",
                        to="core.Market",
                    ),
                ),
                (
                    "supplier_fulfillment_center_sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="core.SupplierFulfillmentCenterSalesChannel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesChannelSupplierArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_number", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("price_old", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "sales_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.SalesChannel",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.Supplier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FulfillmentCenterArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_number", models.CharField(max_length=255)),
                (
                    "barcodes",
                    models.ManyToManyField(
                        related_name="fulfillment_center_barcodes", to="core.Barcode"
                    ),
                ),
                (
                    "fulfillment_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.FulfillmentCenter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fulfillmentcenter",
            name="warehouse",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fulfillment_center",
                to="core.Warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="barcode",
            constraint=models.UniqueConstraint(
                fields=("barcode", "type"), name="core_barcode_barcode_type_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleschannelsupplierarticle",
            constraint=models.UniqueConstraint(
                fields=("sales_channel", "supplier", "article_number"),
                name="core_saleschannelsupplierarticle_sales_channel_supplier_article_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleschannel",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"),
                name="core_saleschannel_content_type_object_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillmentcenterarticle",
            constraint=models.UniqueConstraint(
                fields=("fulfillment_center", "article_number"),
                name="core_fulfillmentcenterarticle_fulfillment_center_article_number_unique",
            ),
        ),
    ]
