# Generated by Django 3.0.1 on 2019-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("warehouse", "warehouse"),
                            ("delivery_center", "delivery center"),
                            ("fulfillment_center", "fulfillment center"),
                            ("supplier", "supplier"),
                            ("online_shop", "online shop"),
                        ],
                        max_length=255,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "backend",
                    models.CharField(
                        choices=[("subprocess", "subprocess")],
                        default="subprocess",
                        max_length=255,
                    ),
                ),
                ("scheme", models.CharField(max_length=255)),
                ("netloc", models.CharField(max_length=255)),
                (
                    "healthcheck_path",
                    models.CharField(blank=True, default="/health/", max_length=255),
                ),
                (
                    "kill_path",
                    models.CharField(blank=True, default="/kill/", max_length=255),
                ),
                (
                    "wanted_status",
                    models.CharField(
                        choices=[("down", "down"), ("up", "up")],
                        default="up",
                        max_length=255,
                    ),
                ),
                (
                    "last_known_status",
                    models.CharField(
                        choices=[("down", "down"), ("up", "up")],
                        default="down",
                        editable=False,
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
