# Generated by Django 3.0.1 on 2019-12-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="backend",
            field=models.CharField(
                choices=[("subprocess", "subprocess"), ("docker", "docker")],
                default="subprocess",
                max_length=255,
            ),
        ),
    ]
